-- +goose Up
create table if not exists profiles (
    id bigint primary key generated by default as identity,
    email text not null check (length(email) < 255),
    name text not null
);
-- +goose Down
drop table if exists profiles;