-- +goose Up
create table if not exists models (
    id bigint primary key generated by default as identity,
    name text not null check (length(name) < 255),
    manufacturer_id bigint not null references manufacturers(id) on delete cascade
);

-- +goose Down
drop table if exists models;
