-- +goose Up
drop table if exists manufacturers;
create table if not exists manufacturers (
    id bigint primary key generated by default as identity,
    name text not null check (length(name) < 255)
);

-- +goose Down
drop table if exists manufacturers;